/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.SG;
import business.comercial.ComponenteNaoExisteException;
import business.comercial.ConfiguracaoNaoExisteException;
import java.util.Collection;
import javax.swing.DefaultListModel;

/**
 *
 * @author josepereira
 */
public class JAlternativas extends javax.swing.JFrame {

    private JLogin jFacade;
    private JCriarConfiguracao parent;
    
    private String componenteId;
    private Collection<String> incompativeis;
    private Collection<String> necessarios;
    /**
     * Creates new form Alternativas
     */
    public JAlternativas(SG sg, Collection<String> incompativeis, Collection<String> necessarios, String componenteId, JLogin jFacade, JCriarConfiguracao parent) {
        initComponents();
        
        this.setResizable(false);
        this.jTextPane1.setEditable(false);
        
        this.jFacade = jFacade;
        this.parent = parent;
        this.componenteId = componenteId;
        this.incompativeis = incompativeis;
        this.necessarios = necessarios;
        
        this.updateIncompativeis();
        this.updateNecessarios();
        if (this.componenteId.equals("-1") == false) this.jLabelComponente.setText("Componente a adicionar: " + this.componenteId);
        else this.jLabelComponente.setText("A adicionar pacote");
    }
    
    public void updateIncompativeis() {   
        DefaultListModel model = new DefaultListModel(); // abstracao visual dos dados
        for(String id: this.incompativeis)    
            model.addElement(id);
        this.jListIncompativeis.setModel(model); 
    }
    
    public void updateNecessarios() {
        DefaultListModel model = new DefaultListModel(); // abstracao visual dos dados
        for(String id: this.necessarios)    
            model.addElement(id);
        this.jListNecessarios.setModel(model); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListIncompativeis = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNecessarios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelComponente = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jListIncompativeis);

        jScrollPane2.setViewportView(jListNecessarios);

        jLabel1.setText("Componentes incompativeis:");

        jLabel2.setText("Componentes necessários:");

        jTextPane1.setText("O componente que pertende adicionar tem os seguintes componentes icompatíveis e necessários.\nEscolha sim, se  deseja ficar com o componente que tentou adicionar e os seus incompativeis serão removidos e os necessários adicionados.\nEscolha não, caso deseja permanecer com a configuração atual.");
        jScrollPane3.setViewportView(jTextPane1);

        jButton1.setText("SIM!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NÃO!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComponente))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabelComponente))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // SIM 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (this.componenteId.equals("-1") == false) this.necessarios.add(componenteId);     
            this.jFacade.getSingleton().addEscolha(this.necessarios, this.incompativeis, this.parent.chaveConfiguracao);
            this.parent.updateConfiguracao();
            this.setVisible(false);
        } catch (ComponenteNaoExisteException e) {
            e.printStackTrace();
        } catch (ConfiguracaoNaoExisteException e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    // NAO
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelComponente;
    private javax.swing.JList<String> jListIncompativeis;
    private javax.swing.JList<String> jListNecessarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
