/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.recursoshumanos.Utilizador;
import business.recursoshumanos.UtilizadorNaoExisteException;

/**
 *
 * @author josepereira
 */
public class JMenuFuncionarioStand extends javax.swing.JFrame {

    private JLogin jLogin;
    private String id;
    
    /**
     * Creates new form JMenuFuncionarioStand
     */
    public JMenuFuncionarioStand(JLogin jLogin, String id) {
        initComponents();
        
        this.setResizable(false);
        this.jLogin = jLogin;
        this.id = id;
        this.updateInfo();
    }
    
    private void updateInfo() {
      
        try {
            
            if (this.jLogin.getSingleton().getDAOFacade().getUtilizadores().containsKey(this.id) == false) 
                throw new UtilizadorNaoExisteException(this.id);
            
            Utilizador u = this.jLogin.getSingleton().getDAOFacade().getUtilizadores().get(this.id);
            this.jLabelNome.setText("nome: " + u.getNome());
            this.jLabelId.setText("id: " + u.getId());
        
        } catch (UtilizadorNaoExisteException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarConfButton = new javax.swing.JButton();
        criarConfOtimaButton = new javax.swing.JButton();
        voltarLoginButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        criarConfButton.setText("Criar Configuração");
        criarConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarConfButtonActionPerformed(evt);
            }
        });

        criarConfOtimaButton.setText("Criar Configuração ótima");
        criarConfOtimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarConfOtimaButtonActionPerformed(evt);
            }
        });

        voltarLoginButton.setText("Voltar ao Login");
        voltarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarLoginButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Login como Funcionário do Stand");

        jLabelNome.setText("nome:");

        jLabelId.setText("id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltarLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criarConfOtimaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criarConfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNome)
                    .addComponent(jLabel3)
                    .addComponent(jLabelId))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criarConfButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(criarConfOtimaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltarLoginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sairButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarConfButtonActionPerformed

        new JCriarConfiguracao(this.jLogin, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_criarConfButtonActionPerformed

    private void voltarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarLoginButtonActionPerformed
        // TODO add your handling code here:
        this.jLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_voltarLoginButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void criarConfOtimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarConfOtimaButtonActionPerformed
        new JCriarConfiguracaoOtima(this.jLogin, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_criarConfOtimaButtonActionPerformed

    public String getId() {
        return this.id;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarConfButton;
    private javax.swing.JButton criarConfOtimaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton voltarLoginButton;
    // End of variables declaration//GEN-END:variables
}
