/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.recursoshumanos.Utilizador;
import business.recursoshumanos.UtilizadorNaoExisteException;

/**
 *
 * @author josepereira
 */
public class JMenuFuncionarioFabrica extends javax.swing.JFrame {

    private JLogin jLogin;
    private String id;
    
    /**
     * Creates new form JMenuFuncionarioFabrica
     */
    public JMenuFuncionarioFabrica(JLogin jLogin, String id) {
        initComponents();
        
        this.setResizable(false);
        this.jLogin = jLogin;
        this.id = id;
        
        this.updateInfo();
    }
    
    private void updateInfo() {
      
        try {
            
            if (this.jLogin.getSingleton().getDAOFacade().getUtilizadores().containsKey(this.id) == false) 
                throw new UtilizadorNaoExisteException(this.id);
            
            Utilizador u = this.jLogin.getSingleton().getDAOFacade().getUtilizadores().get(this.id);
            this.jLabelNome.setText("nome: " + u.getNome());
            this.jLabelId.setText("id: " + u.getId());
        
        } catch (UtilizadorNaoExisteException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicProdButton = new javax.swing.JButton();
        AddStockButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InicProdButton.setText("Iniciar Produções");
        InicProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicProdButtonActionPerformed(evt);
            }
        });

        AddStockButton.setText("Adicionar Stock");
        AddStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStockButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Voltar ao Login");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Login como Funcionário da Fábrica");

        jLabelNome.setText("nome:");

        jLabelId.setText("id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InicProdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelId))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InicProdButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddStockButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sairButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelId)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStockButtonActionPerformed
        // TODO add your handling code here:
        new JAdicionarStock(this.jLogin, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddStockButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        this.jLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void InicProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicProdButtonActionPerformed
        // TODO add your handling code here:
        new JIniciarProducao(this.jLogin, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicProdButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getId() {
        return this.id;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStockButton;
    private javax.swing.JButton InicProdButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
