/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.recursoshumanos.Utilizador;
import business.recursoshumanos.UtilizadorNaoExisteException;

/**
 *
 * @author josepereira
 */
public class JMenuAdministrador extends javax.swing.JFrame {

    private JLogin jLogin;
    private String id;
    
    /**
     * Creates new form JMenuAdministrador
     */
    public JMenuAdministrador(JLogin jLogin, String id) {
        initComponents();
        
        this.setResizable(false);
        this.jLogin = jLogin;
        this.id = id;
        this.updateInfo();
    }
    
    private void updateInfo() {
      
        try {
            
            if (this.jLogin.getSingleton().getDAOFacade().getUtilizadores().containsKey(this.id) == false) 
                throw new UtilizadorNaoExisteException(this.id);
            
            Utilizador u = this.jLogin.getSingleton().getDAOFacade().getUtilizadores().get(this.id);
            this.jLabelNome.setText("nome: " + u.getNome());
            this.jLabelId.setText("id: " + u.getId());
        
        } catch (UtilizadorNaoExisteException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddUtilizadorButton = new javax.swing.JButton();
        removerUtilizadorButton = new javax.swing.JButton();
        voltarLoginButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddUtilizadorButton.setText("Adicionar novo Utilizador");
        AddUtilizadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUtilizadorButtonActionPerformed(evt);
            }
        });

        removerUtilizadorButton.setText("Remover Utilizador");
        removerUtilizadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUtilizadorButtonActionPerformed(evt);
            }
        });

        voltarLoginButton.setText("Voltar ao Login");
        voltarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarLoginButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Login como Administrador:");

        jLabelNome.setText("nome:");

        jLabelId.setText("id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddUtilizadorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removerUtilizadorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltarLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUtilizadorButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(voltarLoginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(removerUtilizadorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelId)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarLoginButtonActionPerformed
        // TODO add your handling code here:
        this.jLogin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_voltarLoginButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void AddUtilizadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUtilizadorButtonActionPerformed
        new JCriarUtilizador(this.jLogin,this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddUtilizadorButtonActionPerformed

    private void removerUtilizadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUtilizadorButtonActionPerformed
        new JRemoverUtilizador(this.jLogin,this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removerUtilizadorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUtilizadorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JButton removerUtilizadorButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton voltarLoginButton;
    // End of variables declaration//GEN-END:variables
}
